# -*- coding: utf-8 -*-
"""CIE2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgQanqrjslhNtX__ALuB4GuWCGVHPCLB
"""

import pandas  as pd
data=pd.read_csv("/content/titanic.csv")
data

data.describe()

data.info()

data.isnull().sum()

data.duplicated()

data.shape

data.head()

data.dtypes

import numpy as np
import pandas as pd
from scipy import stats
data=pd.read_csv("/content/titanic.csv")
mean = np.mean(data['Age'])
median = np.median(data['Age'])
mode=stats.mode(data['Age'],keepdims = True).mode[0]
mean1 = np.mean(data['Fare'])
median1 = np.median(data['Fare'])
mode1=stats.mode(data['Fare'],keepdims = True).mode[0]
print("Central Trndency:")
print("mean Age:",mean)
print("median Age:",median)
print("mode Age:",mode)
print("mean Fare:",mean1)
print("median Fare:",median1)
print("mode Fare:",mode1)

import pandas as pd
import matplotlib.pyplot as plt
data['Survived']=data['Survived'].replace({1:'Survived',0:'not Servived'})
group_data=data.groupby(['Survived','Pclass'])['PassengerId'].count().unstack()
group_data.plot(kind='bar',figsize=(10,6))
plt.title("Survival counts")
plt.xlabel("Survived")
plt.ylabel("count")
plt.xticks(ticks=[1,0], labels=['Not Survived','Survived'],rotation=0)
plt.legend(title='Pclass')
plt.show()

import pandas as pd
data=pd.read_csv("titanic.csv")
data
null_val=data['Age'].isnull().sum()
data_filled=data['Age'].fillna(data['Age'].mean(numeric_only=True))
null_val, data_filled.head(20)

import numpy as np
mean=np.mean(data['Age'])
std=np.std(data['Age'])
print('mean of the dataset is',mean)
print('std.deviation is',std)

threshold =3
outlier =[]
for i in data['Age']:
  z=(i-mean)/std
  if z > threshold:
    outlier.append(i)
print('outlier in dataset is',outlier)

import seaborn as sns
sns.boxplot(data['Age'])